### ISSUE TITLE
Make it transport-agnostic

### ISSUE THREAD

**Issue by myfreeweb** [google/tarpc#16]
I see you've said on reddit that you're thinking about making this library transport-agnostic. Here's my two cents:

[urpc](https://github.com/kmcallister/urpc) can listen on a single `Read + Write` object, which is perfect for my use case – I have a library called [rusty-sandbox](https://github.com/myfreeweb/rusty-sandbox) which creates a pipe between two processes and gives access to it as a `File`. Please add support for this!

**Comment by tikue** [comment]
Your particular use case would be very easy to support, because the semantics of files fulfill all the assumptions we make regarding TCP.

The reason we haven't already done this is because it's possible for someone to, for instance, have a UDP Reader/Writer, which actually wouldn't be a drop in replacement. We'd still have to consider packet sizes, dropped and duplicate packets, keepalive packets, etc.

So the point I'm making is that `Read + Write` is a bit of a leaky abstraction, and we want to think about it a bit. Perhaps we'll end up going that route and simply document the requirements, but maybe there's a better solution we haven't thought of yet.

**Comment by tikue** [comment]
cc @shaladdle

**Comment by tikue** [comment]
We've decided to do this in a similar fashion to urpc and simply document the requirements of any `impl`.
