### ISSUE TITLE
Why can't the server struct have members?

### ISSUE THREAD

**Issue by Boscop** [google/tarpc#173]
Why can't the server struct have members?

And why can't server methods take `&mut self`?

**Comment by tikue** [comment]
There's no such restriction on struct fields. The readme example doesn't have fields just for simplicity, but you're free to put whatever you want in the struct. It just needs to be `Clone`. This is easily accomplished by impling the service trait for `Arc<ServerStruct>`, but you can of course impl it however you'd like.

The methods must take &self because taking &mut would force many people's server structs to be wrapped in a mutex unnecessarily, because `Arc<Server>` only allows immutable access to the struct. If you'd like mutable access to certain fields, you can always wrap your struct in a mutex yourself.

Hope that helps!

**Comment by Boscop** [comment]
But when I take &self I get an error that the rpc method's signature doesn't match the server trait..

**Comment by tikue** [comment]
Can you show me your code? Also, our gitter channel is typically a fast way to get help: https://gitter.im/tarpc/Lobby

**Comment by tikue** [comment]
I'm going to close this, feel free to open it if you still have concerns.
