### ISSUE TITLE
Does this framework support streaming from client & server?

### ISSUE THREAD

**Issue by thedodd** [google/tarpc#189]
For example, gRPC supports streaming of messages from client to server, as well as streaming from server to client. Anything like that with this framework?

If so, can you point me to an example?

**Comment by tikue** [comment]
I've actually spent a lot of time the last week thinking about streams (no, they're not currently supported).

My initial ideas could largely be described as "HTTP2 but worse." It turns out HTTP2 is *really* good at streaming RPCs. It makes sense, then, that gRPC is built on HTTP2.

Streaming can't really be tacked on; it would require deep changes. I originally was thinking about having a modal protocol where either you're streaming or in a unary request. But that requires a bifurcated code structure, where all the streaming code is completely separate. Now I understand why gRPC *only* supports streams.

I could spend a lot of time adding streaming support to tarpc that is identical to what you get with gRPC, but at that point I'd have to recommend just going with gRPC. Maybe tarpc's destiny is to end up as a gRPC code generator. But for now I want to continue to focus on providing a good experience for folks who just need unary request-responses.

I have a rewrite in progress that removes the dependency on tokio-proto and adds a lot of features currently missing. It probably won't be merged until the futures churn (async await, pinning, etc) settles a bit, but that's where my priorities like right now.
