### ISSUE TITLE
UDP transport

### ISSUE THREAD

**Issue by 0nkery** [google/tarpc#41]
I looked through source code ([this branch](https://github.com/tikue/tarpc/tree/async)) trying to understand how to use UDP as underlying transport. I saw [this](https://github.com/tikue/tarpc/blob/async/src/transport.rs#L19). Does it contain all available variants?

Thought about implementing `TryFrom<Something>` but you've already used it for TCP.

I know that branch is WIP but could you share your ideas about UDP support?

UPD. Not only Stream, but Listener too, of course.

PS. Sorry if my English is bad.

**Comment by tikue** [comment]
Hey, thanks for your interest! I'm glad you were able to find your way to the async branch, because that's the most up to date -- we're working on merging it upstream soon (tm)...

You're correct that the `Stream` enum contains all supported protocols. We did it that way because we figured it'd be easier to just have people file issues when there was a protocol they wanted support for rather than complicating the API with a ton of traits (we tried it, and it was a ton).

Having said that, I don't think we have any plans to support UDP at the moment, because it actually would require a different API than the one exposed by the Stream type. @shaladdle any thoughts?

(your English is great!)

**Comment by shaladdle** [comment]
Hi! I'd like to understand why you want to use UDP as an underlying transport. Is there something about TCP that makes it not work for your use case?

Right now we expose certain semantics to the application layer, and using UDP would either involve reimplementing the parts of TCP that provide those semantics, or changing the semantics Tarpc exposes. Doing the former will add complexity, and we probably won't do it better than the existing TCP stacks. Doing the latter is undesirable because it makes using Tarpc harder/more confusing.

Admittedly though, I'm not a networking expert, so if there's something I'm missing, let me know.

**Comment by 0nkery** [comment]
Thanks for your responses!

I want to build toy distributed system and was wondering if TCP or UDP is more suitable for this case. So it's just a matter of comparison.

So, I will maybe use TCP and Unix Sockets together. Maybe TCP only. Closing this.

Thanks again.
