### ISSUE TITLE
Add a way to derive Clone for the generated Request and Response types

### ISSUE THREAD

**Issue by ShaneMurphy2** [google/tarpc#436]
Currently `tarpc::service` creates request and response types that are not clone. This makes it difficult it difficult to test and mock. It would be nice if the service macro used an attribute macro to control adding derives for things like `PartialEq`, `Clone`, or `Hash`.
Is there any reason not to do this? If there isn't, I can take a stab at it.

**Comment by tikue** [comment]
Thanks for the suggestion! I agree this could be supported.

It'd be nice to replace the `derive_serde` arg with something generic enough to support this new use case. Maybe something like this would be possible:

```rust
#[tarpc::service(derive(tarpc::serde::Serialize, tarpc::serde::Deserialize, Clone, Hash))]
service World {
    async fn hello(message: String) -> String;
}
```

**Comment by ShaneMurphy2** [comment]
@tikue Got a first cut up on a branch: https://github.com/ShaneMurphy2/tarpc/tree/customizable-derives, let me know what you think so far.

**Comment by tikue** [comment]
Looks nice! It'd be nice for `derive_serde` and `derive` to be mutually exclusive, so that people are encouraged to make the switch. In particular:

- `derive_serde` and `derive` at the same time should be an error
- `derive` should only derive Serialize/Deserialize when they are explicitly listed
- `derive_serde` is deprecated - output a warning when it is used, and suggest instead using either `derive = []` to disable, or `derive = [Serialize, Deserialize]` to explicitly enable
- for backwards compatibility, absence of `derive` can derive Serialize/Deserialize by default.

**Comment by ShaneMurphy2** [comment]
@tikue PR is up!
