### ISSUE TITLE
Allow for mutable self reference in services

### ISSUE THREAD

**Issue by andreweduffy** [google/tarpc#45]
Currently, the `Service` trait generated by `service!` passes immutable `&self` references to all methods. However for Service implementations that want to update some internal state in response to an RPC message, they can't update anything on self. Thus it might be nice to have some sort of extra pattern, ex. `rpc mut` that will generate a trait method that allows mutation. Not sure if the behavior I'm asking about is supported in some other way as I'm fairly new to Rust, so feel free to tell me I'm being silly here.

**Comment by tikue** [comment]
Hey, thanks for your interest!

The reason that the `Service` trait takes `&self` instead of `&mut self` is because it's currently backed by a thread pool so that a service can respond to multiple requests concurrently. If it were allowed to have mutable state, it'd allow for the possibility of race conditions, which is unsafe and undefined behavior in Rust. Tarpc is actually in the process of being refactored to be built on top of [tokio](https://github.com/tokio-rs/tokio/tree/master/src), which in turn is built on top of [futures](http://alexcrichton.com/futures-rs/futures/), which requires trait implementations to be `Sync` for similar reasons.

The canonical solution to this is to simply wrap whatever state you're accessing in a concurrent-safe container. The simplest of which would be to use a [`Mutex`](https://doc.rust-lang.org/std/sync/struct.Mutex.html)  or [`RwLock`](https://doc.rust-lang.org/std/sync/struct.RwLock.html).  You could also use atomics, or check out some of the crates on crates.io that provide more advanced synchronization primitives, such as [crossbeam](http://aturon.github.io/crossbeam-doc/crossbeam/).

**Comment by andreweduffy** [comment]
Thanks for the quick reply! To paraphrase, what you wrote, it sounds like things implementing the `Service` trait cannot have mutable data directly on them, so instead you'd need to have some external source of mutable data that the Service takes out a mutable reference on, and then make sure that those accesses are synchronized by one of the primitives you mentioned. Is that correct?

**Comment by tikue** [comment]
Technically, the mutable data can still be directly on the service, but it
has to be *internally* mutable, which usually is done by wrapping it in a
Mutex or some other synchronization primitive.

**Comment by andreweduffy** [comment]
Cool, thanks for the tips! Closing this.
