### ISSUE TITLE
Allowing meta-level processing of services

### ISSUE THREAD

**Issue by CowBoy4mH3LL** [google/tarpc#469]
Say I have two services, 
```
#[tarpc::service]
pub trait A{
...}
#[tarpc::service]
pub trait B{
...}
```

I want to write a function that intakes types of either A or B -- how do I go about it?
Traditional tricks like trait objects, common super trait, etc. don't seem to work.

Is this something that has been discussed in the past?

**Comment by tikue** [comment]
Hi, thanks for the question! Have you seen the extension methods on the Serve trait, `before`, `after`, and `before_and_after`?

**Comment by CowBoy4mH3LL** [comment]
I see those are hook -- I would want to simply accept the two types as a part of the function signature.

**Comment by tikue** [comment]
A function that is generic over the [`Serve`][0] trait should be able to accept both service implementations after calling `serve()` on them (which converts them into a type that implements `Serve`).

[0]: https://docs.rs/tarpc/latest/tarpc/server/trait.Serve.html

**Comment by CowBoy4mH3LL** [comment]
But what if I want to call the serve() in the "A function" and not have the user do it?
This is where the issue is -- I know the traits A,B,..  a priori but cannot create the aforementioned function thus far.

**Comment by tikue** [comment]
Sorry, there is no trait shared by service impls due to Rust's orphan rules. That's why `serve()` is an extension method rather than a blanket impl.

- The service traits live in the user's crate, so tarpc can't reference those traits in a blanket impl.
- The `#[service]` macro itself can't provide an impl because it generates code in the user crate, which is not allowed to provide a blanket impl for the Serve trait, because it would conflict with other crates using tarpc that would also want to provide a blanket impl.

**Comment by CowBoy4mH3LL** [comment]
So that is what I am doing at this time. I am using a glue macro to make up for the "service" macro generated structures that are basically superstrings of A and B.
