### ISSUE TITLE
Excuses me How to handle errors?

### ISSUE THREAD

**Issue by l-7-l** [google/tarpc#489]
The example is so simple, I see Request<T> Result<T> and Response <T>in the docs but I don't know when to use them

**Comment by tikue** [comment]
Hi! Are you asking about client (RPC) errors, or server errors? For RPC errors, there is an [enum](https://github.com/google/tarpc/blob/8e868bfeb3f95f95101ae15ce56ef90c30df07de/tarpc/src/client.rs#L180) for all the client errors that can occur. For server errors, on your service definition, you can make the return type a `Result<Response, YourErrorType>`.

BTW this could be a good question for a [discussion](https://github.com/google/tarpc/discussions) instead of an issue.

**Comment by l-7-l** [comment]
thanks buddy
